[package]
name = "libs"
version = "1.0.0"
authors = []

[addresses]
lib_addr = "0xfbd8a22c43d13114d69739e594e4e0df92d22a2aa8d9b5baad590d4cb425be94"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
