[package]
name = "libs"
version = "1.0.0"
authors = []

[addresses]
lib_addr = "0x03bcb547e66352f5f0a71e2b955c8f830dc640f3380c847e4e7103a8e2b53a81"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
