[package]
name = "libs"
version = "1.0.0"
authors = []

[addresses]
lib_addr = "0x1c4980a5b242e790c03801d45e1403e66c5bcb2d00ec701e30763c5439fc97ce"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
