[package]
name = "libs"
version = "1.0.0"
authors = []

[addresses]
lib_addr = "0xa71fa6b4557dbffd49dddeb631e0c83b86d9ed99f0b56c915fa3d296e0586136"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"
